
var hGen = {
  hprotein:'GHRRLCTPQPLRKMGARRSRSPPVPPPLFSSFLSLFSAPPVPSAPDVGEGLPQASL',
  hfactor:'QGHGTCIDGIGSFSCDCRSGWEGRFCQREVSFLNCSLDNGGCTHYCLEEVGWRRCSCAPGYKLGDDLLQCHPAVKFPCGRPWKRMEKKRSHLKRDTEDQEDQVDPRLIDGKMTRRGDSPWQVVLLDSKKKLACGAVLIHPSWVLTAAHCMDESKKLLVRLGEYDLRRWEKWELDLDIKEVFVHPNYSKSTTDNDIALLHLAQPATLSQTIVPICLPDSGLAERELNQAGQETLVTGWGYHSSREKEAKRNRTFVLNFIKIPVVPHNECSEVMSNMVSENMLCAGILGDRQDACEGDSGGPMVASFHGTWFLVGLVSWGEGCGLLHNYGVYTKVSRYLDWIHGHIRDKEAPQKSWAP',
  hinsulin: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN',
  hreceptor: 'MTMTLHTKASGMALLHQIQGNELEPLNRPQLKIPLERPLGEVYLDSSKPAVYNYPEGAAYEFNAAAAANAQVYGQTGLPYGPGSEAAAFGSNGLGGFPPLNSVSPSPLMLLHPPPQLSPFLQPHGQQVPYYLENEPSGYTVREAGPPAFYRPNSDNRRQGGRERLASTNDKGSMAMESAKETRYCAVCNDYASGYHYGVWSCEGCKAFFKRSIQGHNDYMCPATNQCTIDKNRRKSCQACRLRKCYEVGMMKGGIRKDRRGGRMLKHKRQRDDGEGRGEVGSAGDMRAANLWPSPLMIKRSKKNSLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLYDLLLEMLDAHRLHAPTSRGGASVEETDQSHLATAGSTSSHSLQKYYITGEAEGFPATV',
  himmu: 'EIVLTQSPGTLSLSPGERATLSCRASQSVSSSTLAWYQQKVGQAPRLLIYGASSRVTGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGGSPPWTFGQGTKVEIKR',
  hcell : 'GTAGQSLEQPSEVTAVEGAIVQINCTYQTSGFYGLSWYQQHDGGAPTFLSYNALDGLEETGRFSSFLSRSDSYGYLLLQELQMKDSASYFCAARDTGFQKLVFGTGTRLLVSP',
  nucle :'MADHSFSDGVPSDSVEAAKNASNTEKLTDQVMQNPRVLAALQERLDNVPHTPSSYIETLPKAVKRRINALKQLQVRCAHIEAKFYEEVHDLERKYAALYQPLFDKRREFITGDVEPTDAESEWHSENEEEEKLAGDMKSKVVVTEKAAATAEEPDPKGIPEFWFTIFRNVDMLSELVQEYDEPILKHLQDIKVKFSDPGQPMSFVLEFHFEPNDYFTNSVLTKTYKMKSEPDKADPFSFEGPEIVDCDGCTIDWKKGKNVTVKTIKKKQKHKGRGTVRTITKQVPNESFFNFFNPLKASGDGESLDEDSEFTLASDFEIGHFFRERIVPRAVLYFTGEAIEDDDNFEEGEEGEEEELEGDEEGEDEDDAEINPKV'
};

var mGen = {
  mprotein:'MAQGSGDQRAVGIADPEESSPNMIVYCKIEDIITKMQDDKTGGVPIRTVKSFLSKIPSVVTGTDIVQWLMKNLSIEDPVEAIHLGSLIAAQGYIFPISDHVLTMKDDGTFYRFQAPYFWPSNCWEPENTDYAIYLCKRTMQNKARLELADYEAENLARLQRAFARKWEFIFMQAEAQVKIDRKKDKTERKILDSQERAFWDVHRPVPGCVNTTEMDIRKCRRLKNPQKVKKSVYGVTDETQSQSPVHIPSQPIRKTTKDDIRKQITFLNAQIDRHCLKMSKVAESLIAYTEQYVEYDPFITPAEPSNPWISDDITLWDIEMSKEPSQQRVKRWGFSFDEILKDQVGRDQFLRFLESEFSSENLRFWLSVQDLKKQPLQDVAKRVEEIWQEFLAPGAPSAINLDSHSYEITSQNVKDGGRYTFEDAQEHIYKLMKSDSYARFLRSNAYQDLLLAKKKPESEQGRRTSLEKFTRSVGKSLAGKRLTGLMQSS',
  mfactor:'DHWELDLDIKEILVHPNYTRSSSDNDIALLRLAQPATLSKTIVPICLPNNGLAQQELTQAGQETVVTGWGYQSDRIKDGRRNRTFILTFIRIPLVARNECVEVMKNVVSENMLCAGIIGNTRDACDGDSGGPMVVFFRGTWFLVGLVSWGEGCGHTNNYGI',
  minsulin: 'MALWMRLLPLLALLVLWEPKPAQAFVNQHLCGSHLVEALYLVCGERGFFYTPKSRRGVEDPQVAQLELGGGPGAGDLQTLALEVAQQKRGIVDQCCTSICSLYQLENYCN',
  mreceptor: 'MTMTLHTKASGMALLHQIQGNELEPLNRPQLKMPMERALGEVYVDNSKPTVFNYPEGAAYEFNAAAAAAAAASAPVYGQSGIAYGPGSEAAAFSANSLGAFPQLNSVSPSPLMLLHPPPQLSPFLHPHGQQVPYYLENEPSAYAVRDTGPPAFYRSNSDNRRQNGRERLSSSNEKGNMIMESAKETRYCAVCNDYASGYHYGVWSCEGCKAFFKRSIQGHNDYMCPATNQCTIDKNRRKSCQACRLRKCYEVGMMKGGIRKDRRGGRMLKHKRQRDDLEGRNEMGASGDMRAANLWPSPLVIKHTKKNSPALSLTADQMVSALLDAEPPMIYSEYDPSRPFSEASMMGLLTNLADRELVHMINWAKRVPGFGDLNLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHRRLAQLLLILSHIRHMSNKGMEHLYNMKCKNVVPLYDLLLEMLDAHRLHAPASRMGVPPEEPSQTQLATTSSTSAHSLQTYYIPPEAEGFPNTI',
  mimmu: 'DVLMTQTPLSLPVSLGDQASISCRSSQSIVHSNGNTYLEWYLQKPGQSPKLLIYKVSNRFSGVPDRFSGSGSGTDFTLKIRRVEAEDLGVYYCFQGSHVPYTFGGGTKLEIK',
  mcell : 'SAFDYFPWYQQFPGEGPALLIAIRSVSDKKEDGRFTIFFNKREKKLSLHITDSQPGDSATYFCAARDSSNTNKVVFGTGTR',
  mucle :'MAENSLSDGGPADSVEAAKNASNTEKLTDQVMQNPQVLAALQERLDNVSHTPSSYIETLPKAVKRRINALKQLQVRCAHIEAKFYEEVHDLERKYAALYQPLFDKRREFITGDVEPTDAESAWHSENEEEDKLAGDMKNKVVIAEKEAATVEELNPKGIPEFWFTIFRNVDMLSELVQEYDEPILKHLQDIKVKFSDPGQPMSFVLEFHFEPNDYFTNPVLTKTYKMKSEPDKADPFSFEGPEIVDCDGCTIDWKKGKNVTVKTIKKKQKHKGRGTVRTITKQVPNESFFNFFSPLKASGDGESLDEDSEFTLASDFEIGHFFRERIVPRAVLYFTGEAIEDDDNFEEGEEGEEEELEGDEEGEDEDDADVNPKKEPSQPAECKQQ'
};






var i = 0;



function playing1(){
    var b = document.getElementById("button1");
    if(b.classList.contains('playing')){
      i=999999;
      b.classList.remove("playing");
    }
    else{
      i=0;
      b.classList.add("playing");
    }

}


function playing2(){
    var b = document.getElementById("button2");
    if(b.classList.contains('playing')){
      i=999999;
      b.classList.remove("playing");
    }
    else{
      i=0;
      b.classList.add("playing");
    }

}



function mSound(){
  var e = document.getElementById("mSelect");
  playing2();
  var selectedValue = e.options[e.selectedIndex].value;
  console.log(mGen[selectedValue]);
  console.log(selectedValue);
  playMSound(selectedValue);
}


function playMSound(selectedValue){
  setTimeout(function () {
    var audio = new Audio(`music/${mGen[selectedValue][i]}.mp3`);
    audio.preload = 'auto';
audio.load();
   audio.play();
  console.log(i);
     i++;
     if (i < mGen[selectedValue].length) {
        playMSound(selectedValue);
     }
  }, 500);
}


function hSound(){
  playing1();
  var e = document.getElementById("hSelect");
  var selectedValue = e.options[e.selectedIndex].value;
  console.log(hGen[selectedValue]);
  console.log(selectedValue);
  playHSound(selectedValue);
}


function playHSound(selectedValue){
  setTimeout(function () {
    var audio = new Audio(`music/${hGen[selectedValue][i]}.mp3`);
   audio.play();
  console.log(i);
     i++;
     if (i < hGen[selectedValue].length) {
        playHSound(selectedValue);
     }
  }, 300);
}
