
var hGen = {
  hprotein:'GHRRLCTPQPLRKMGARRSRSPPVPPPLFSSFLSLFSAPPVPSAPDVGEGLPQASL',
  hfactor:'QGHGTCIDGIGSFSCDCRSGWEGRFCQREVSFLNCSLDNGGCTHYCLEEVGWRRCSCAPGYKLGDDLLQCHPAVKFPCGRPWKRMEKKRSHLKRDTEDQEDQVDPRLIDGKMTRRGDSPWQVVLLDSKKKLACGAVLIHPSWVLTAAHCMDESKKLLVRLGEYDLRRWEKWELDLDIKEVFVHPNYSKSTTDNDIALLHLAQPATLSQTIVPICLPDSGLAERELNQAGQETLVTGWGYHSSREKEAKRNRTFVLNFIKIPVVPHNECSEVMSNMVSENMLCAGILGDRQDACEGDSGGPMVASFHGTWFLVGLVSWGEGCGLLHNYGVYTKVSRYLDWIHGHIRDKEAPQKSWAP',
  hinsulin: 'MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGGGPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN',
  hreceptor: 'MTMTLHTKASGMALLHQIQGNELEPLNRPQLKIPLERPLGEVYLDSSKPAVYNYPEGAAYEFNAAAAANAQVYGQTGLPYGPGSEAAAFGSNGLGGFPPLNSVSPSPLMLLHPPPQLSPFLQPHGQQVPYYLENEPSGYTVREAGPPAFYRPNSDNRRQGGRERLASTNDKGSMAMESAKETRYCAVCNDYASGYHYGVWSCEGCKAFFKRSIQGHNDYMCPATNQCTIDKNRRKSCQACRLRKCYEVGMMKGGIRKDRRGGRMLKHKRQRDDGEGRGEVGSAGDMRAANLWPSPLMIKRSKKNSLALSLTADQMVSALLDAEPPILYSEYDPTRPFSEASMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKCKNVVPLYDLLLEMLDAHRLHAPTSRGGASVEETDQSHLATAGSTSSHSLQKYYITGEAEGFPATV',
  himmu: 'EIVLTQSPGTLSLSPGERATLSCRASQSVSSSTLAWYQQKVGQAPRLLIYGASSRVTGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGGSPPWTFGQGTKVEIKR',
  hcell : 'GTAGQSLEQPSEVTAVEGAIVQINCTYQTSGFYGLSWYQQHDGGAPTFLSYNALDGLEETGRFSSFLSRSDSYGYLLLQELQMKDSASYFCAARDTGFQKLVFGTGTRLLVSP',
  nucle :'MADHSFSDGVPSDSVEAAKNASNTEKLTDQVMQNPRVLAALQERLDNVPHTPSSYIETLPKAVKRRINALKQLQVRCAHIEAKFYEEVHDLERKYAALYQPLFDKRREFITGDVEPTDAESEWHSENEEEEKLAGDMKSKVVVTEKAAATAEEPDPKGIPEFWFTIFRNVDMLSELVQEYDEPILKHLQDIKVKFSDPGQPMSFVLEFHFEPNDYFTNSVLTKTYKMKSEPDKADPFSFEGPEIVDCDGCTIDWKKGKNVTVKTIKKKQKHKGRGTVRTITKQVPNESFFNFFNPLKASGDGESLDEDSEFTLASDFEIGHFFRERIVPRAVLYFTGEAIEDDDNFEEGEEGEEEELEGDEEGEDEDDAEINPKV'
};

var mGen = {
  mprotein:'MAQGSGDQRAVGIADPEESSPNMIVYCKIEDIITKMQDDKTGGVPIRTVKSFLSKIPSVVTGTDIVQWLMKNLSIEDPVEAIHLGSLIAAQGYIFPISDHVLTMKDDGTFYRFQAPYFWPSNCWEPENTDYAIYLCKRTMQNKARLELADYEAENLARLQRAFARKWEFIFMQAEAQVKIDRKKDKTERKILDSQERAFWDVHRPVPGCVNTTEMDIRKCRRLKNPQKVKKSVYGVTDETQSQSPVHIPSQPIRKTTKDDIRKQITFLNAQIDRHCLKMSKVAESLIAYTEQYVEYDPFITPAEPSNPWISDDITLWDIEMSKEPSQQRVKRWGFSFDEILKDQVGRDQFLRFLESEFSSENLRFWLSVQDLKKQPLQDVAKRVEEIWQEFLAPGAPSAINLDSHSYEITSQNVKDGGRYTFEDAQEHIYKLMKSDSYARFLRSNAYQDLLLAKKKPESEQGRRTSLEKFTRSVGKSLAGKRLTGLMQSS',
  mfactor:'DHWELDLDIKEILVHPNYTRSSSDNDIALLRLAQPATLSKTIVPICLPNNGLAQQELTQAGQETVVTGWGYQSDRIKDGRRNRTFILTFIRIPLVARNECVEVMKNVVSENMLCAGIIGNTRDACDGDSGGPMVVFFRGTWFLVGLVSWGEGCGHTNNYGI',
  minsulin: 'MALWMRLLPLLALLVLWEPKPAQAFVNQHLCGSHLVEALYLVCGERGFFYTPKSRRGVEDPQVAQLELGGGPGAGDLQTLALEVAQQKRGIVDQCCTSICSLYQLENYCN',
  mreceptor: 'MTMTLHTKASGMALLHQIQGNELEPLNRPQLKMPMERALGEVYVDNSKPTVFNYPEGAAYEFNAAAAAAAAASAPVYGQSGIAYGPGSEAAAFSANSLGAFPQLNSVSPSPLMLLHPPPQLSPFLHPHGQQVPYYLENEPSAYAVRDTGPPAFYRSNSDNRRQNGRERLSSSNEKGNMIMESAKETRYCAVCNDYASGYHYGVWSCEGCKAFFKRSIQGHNDYMCPATNQCTIDKNRRKSCQACRLRKCYEVGMMKGGIRKDRRGGRMLKHKRQRDDLEGRNEMGASGDMRAANLWPSPLVIKHTKKNSPALSLTADQMVSALLDAEPPMIYSEYDPSRPFSEASMMGLLTNLADRELVHMINWAKRVPGFGDLNLHDQVHLLECAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNQGKCVEGMVEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFLSSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHRRLAQLLLILSHIRHMSNKGMEHLYNMKCKNVVPLYDLLLEMLDAHRLHAPASRMGVPPEEPSQTQLATTSSTSAHSLQTYYIPPEAEGFPNTI',
  mimmu: 'DVLMTQTPLSLPVSLGDQASISCRSSQSIVHSNGNTYLEWYLQKPGQSPKLLIYKVSNRFSGVPDRFSGSGSGTDFTLKIRRVEAEDLGVYYCFQGSHVPYTFGGGTKLEIK',
  mcell : 'SAFDYFPWYQQFPGEGPALLIAIRSVSDKKEDGRFTIFFNKREKKLSLHITDSQPGDSATYFCAARDSSNTNKVVFGTGTR',
  mucle :'MAENSLSDGGPADSVEAAKNASNTEKLTDQVMQNPQVLAALQERLDNVSHTPSSYIETLPKAVKRRINALKQLQVRCAHIEAKFYEEVHDLERKYAALYQPLFDKRREFITGDVEPTDAESAWHSENEEEDKLAGDMKNKVVIAEKEAATVEELNPKGIPEFWFTIFRNVDMLSELVQEYDEPILKHLQDIKVKFSDPGQPMSFVLEFHFEPNDYFTNPVLTKTYKMKSEPDKADPFSFEGPEIVDCDGCTIDWKKGKNVTVKTIKKKQKHKGRGTVRTITKQVPNESFFNFFSPLKASGDGESLDEDSEFTLASDFEIGHFFRERIVPRAVLYFTGEAIEDDDNFEEGEEGEEEELEGDEEGEDEDDADVNPKKEPSQPAECKQQ'
};






var i = 0;



function playing1(id){
    var b = document.getElementById(id);
    if(b.classList.contains('playing')){
      i=999999;
      b.classList.remove("playing");
    }
    else{
      i=0;
      b.classList.add("playing");
    }

}


function playing2(e){
    var b = document.getElementById(e);
    if(b.classList.contains('playing')){
      i=999999;
      b.classList.remove("playing");
    }
    else{
      i=0;
      b.classList.add("playing");
    }

}



function mSound(e){
  playing2(e.id);
  playMSound(e.id);
}


function playMSound(selectedValue){
  setTimeout(function () {
    var audio = new Audio(`music/${mGen[selectedValue][i]}.mp3`);
    audio.preload = 'auto';
audio.load();
   audio.play();
  console.log(i);
     i++;
     if (i < mGen[selectedValue].length) {
        playMSound(selectedValue);
     }
  }, 300);
}


function hSound(e){
  console.log(e.id);
  playing1(e.id);

  playHSound(e.id);
}


function playHSound(selectedValue){
  setTimeout(function () {
    var audio = new Audio(`music/${hGen[selectedValue][i]}.mp3`);
   audio.play();
  console.log(i);
     i++;
     if (i < hGen[selectedValue].length) {
        playHSound(selectedValue);
     }
  }, 300);
}
